### ISSUE TITLE
Add Nginx container

### ISSUE THREAD

**Issue by leominov** [leominov/fabric-bolt#1]
```
nginx:
  build: ./nginx
  restart: always
  entrypoint: ["/usr/sbin/nginx"]
  ports:
    - "80:80"
    - "443:443"
  links:
    - web
```
